### ISSUE TITLE
failure_reason is present even if the grammar parsed successfully

### ISSUE THREAD

**Issue by serguei-at-bemaximus** [cjheath/treetop#45]
Maybe this is not a bug as in "not intended" but I definitely got "burned" by this :) (2 hours of confusion)

I was testing my grammar with some unit tests and didn't think nothing of writing an assert like
```
p = parser.parse s
assert_nil parser.failure_reason
...
```

Which resulted in the "failure reason" looking something like "expected <something> at the 1 "column" just beyond the end of input/file. I kept thinking that this is some kind of usual "greediness" mistake and my grammar is not specifying the repetition correctly.

Anyway, point is, maybe the word "failure" in "failure_reason" is misleading. If I had to guess, maybe you meant something like "the reason parser stopped" so maybe `stop_reason` or something like that would be better.

I like this library a lot, judging by ruby-toolbox.com, it's the only game in town as far as PEG parsers, so I'd love this project to flourish.

Cheers!

**Comment by cjheath** [comment]
Every failed path ends in a terminal node failure, but every successful parse also has a reason why it didn't progress further. Treetop keeps just one, at the most advanced input position, because that is commonly a useful hint as to a possible syntax error in the input - though of course an actual syntax error may lead to an earlier failure that is not retained or reported.

So that's the thing; it's really only a hint. There is no way to definitively point to a syntax error, because any of the failed paths at any point in the input could be because of an error path that started much earlier.

**Comment by serguei-at-bemaximus** [comment]
I guess the word "failure" has a specific meaning in the context of parsers like this. I just interpreted it the way I think a dev unfamiliar with these parsers would, which is "parsing couldn't be done. either input is bad or grammar is bad". I wasn't asking for any behavior change, just maybe consider a better name or a callout in the documentation.

**Comment by cjheath** [comment]
Understood. Much too late for a change now however.

The name is correct in the light of top-down parsing. A "successful" parse can be a component of a failing rule, and its progress the furthest point reached, so although this rule succeeded, it is still an overall parse failure.
